import Head from "next/head";
import Image from "next/image";
import About from "../src/components/About/About";
import BackgroundAnimation from "../src/components/BackgroundAnimation/BackgroundAnimation";
import Main from "../src/components/Main/Main";
import Navbar from "../src/components/Navbar/Navbar";
import Projects from "../src/components/Projects/Projects";
import Skills from "../src/components/Skills/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sourav | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BackgroundAnimation />
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
    </div>
  );
}
